### ISSUE TITLE
Path variables are not rendered the same when there are parameters

### ISSUE THREAD

**Issue by HassenIO** [yaakapp/app#101]
### What happened?

Hi,

Variables in the path are not rendered the same, when there are also parameters or not.

Here is how it looks like when there are no parameters:

![CleanShot 2024-09-20 at 09 51 04@2x](https://github.com/user-attachments/assets/9df81876-e31f-47bb-aa79-03354151cffb)

And here when there is a parameter:

![CleanShot 2024-09-20 at 09 51 20@2x](https://github.com/user-attachments/assets/e4617f37-6d8a-436c-94b6-84cbdcb6f166)

The URL was hand written; ie not obtained from a migration or any plugin.

I'm currently using version `2024.10.0-beta.3`

### Version

2024.10.0-beta.3

### What operating system are you on?

macOS

**Comment by gschier** [comment]
Thanks for the bug report!
