### ISSUE TITLE
Yaak trips Crowdstrike on Windows due to the app not being signed

### ISSUE THREAD

**Issue by LukeIGS** [yaakapp/app#102]
### What happened?

Attempting to run Yaak on a Crowdstrike secured Windows host will cause Crowdstrike to flag it and immediately kill the process.   Running the exe through Virus Total reveals that it's because Yaak (at least on windows) isn't signed.

### Version

2024.9.1

### What operating system are you on?

Windows

**Comment by gschier** [comment]
This is being tracked at https://feedback.yaak.app/p/sign-windows-release

signing Windows releases is a big pain as of recent, so I've been avoiding it as long as possible. I'm hoping to get it done in the next few months, though.

**Comment by LukeIGS** [comment]
Cool, at least it won't get duplicated over here again then.

**Comment by gschier** [comment]
@LukeIGS do you have a way to bypass Crowdstrike to use it anyway?

**Comment by LukeIGS** [comment]
I am not able to on my work machine, I plan to mess around with it using one of my personal machines.

**Comment by gschier** [comment]
K, I'm going to bump this in priority then, as I'm sure there are more people unable to use it
