### ISSUE TITLE
Changes to GraphQL variables field gets lost if the edited content is not valid JSON

### ISSUE THREAD

**Issue by martinsp** [yaakapp/app#103]
### What happened?

Hi,

I really like using Yaak, you have created a great application.

I have encountered an issue with input of GraphQL variables.

Steps to reproduce:

1. create new GraphQL request
2. make some changes to "Variables" field, ensure that the content is not a valid JSON
3. switch to some other request
4. switch back to the GraphQL request
5. the changes are gone

Quite often I find myself switching to other GraphQL request to copy part of variables, when I haven't completely finished writing the content for "Variables" field for new GraphQL request. It's quite annoying that the changes I did just a moment ago are lost.

### Version

2024.9.1 (20240917.143011)

### What operating system are you on?

macOS

**Comment by gschier** [comment]
Ah yes. There is currently a limitation where the variables don't save if the JSON is invalid. I'll get that fixed.
