### ISSUE TITLE
URL param

### ISSUE THREAD

**Issue by baek-sang** [yaakapp/app#105]
### What happened?

https://github.com/user-attachments/assets/a765200e-e6e6-4f0f-aab1-3d2d3009f38e

1. Params not updated, params from old URL remains.
2. The param in the URL is removed. The URL should remain intact so that it can be copied and used by other programs.

### Version

2024.10.0-beta.4

### What operating system are you on?

Windows

**Comment by gschier** [comment]
This is now live in https://yaak.app/blog/2024.10.0-beta.6
