### ISSUE TITLE
Request chain stuck when populating global var

### ISSUE THREAD

**Issue by moltob** [yaakapp/app#107]
### What happened?

First of all thank you for this wonderful application!

I am switching over from another tool and try to set up request chaining. Sporadically, setup of a request causes the chain to hang the application. Once happening, I cannot stop the request in any other (known) way than closing the application window.

These are the two requests, hanging with the spinning wheel:

![image](https://github.com/user-attachments/assets/705b322c-09f4-47a1-8d1b-782fdfab4a4b)

Now, this happens sporadically, kind of.

It happened immediately, when I first tried out the chaining feature. In fact, at the very first time even the auto-complete for the `response` function was unavailable... A restart made it appear. Then the requests started hanging.

Right at this moment (but I am unsure this is really just this context) I can 100% reproduce it by:

- Setting up the first request (access token)
- Setting up the second request
- Defining a global variable (this makes a difference right now!) `ACCESS_TOKEN` and assigning a body attribute of the first request.
- Use the `ACCESS_TOKEN` variable in the bearer token auth of the second request.

If I make `ACCESS_TOKEN` an environment-specific variable it works!

![image](https://github.com/user-attachments/assets/83dc1132-ff90-4a36-acde-8092b7694df0)

However, I am pretty sure I have seen other combinations where it got stuck as well. The only thing surely involved is using the chaining function `response`.

The developer tools console log does not show anything. Logs neither.

### Version

2024.9.1

### What operating system are you on?

Windows

### Relevant log output

Logs when I start a failing request and then exit the app to kill it.

```
[2024-09-24][11:55:51][[33mWARN[0m][tao::platform_impl::platform::event_loop::runner] NewEvents emitted without explicit RedrawEventsCleared
[2024-09-24][11:55:51][[33mWARN[0m][tao::platform_impl::platform::event_loop::runner] RedrawEventsCleared emitted without explicit MainEventsCleared
[2024-09-24][11:55:57][[37mINFO[0m][yaak_plugin_runtime::plugin] Exiting plugin runtime due to app exit
```

**Comment by gschier** [comment]
I think I figured it out. For me, it only happens if there are no responses in the request being referenced (has to send one on render). Trying to fix now

**Comment by gschier** [comment]
This is now available in Beta 5! https://yaak.app/blog/2024.10.0-beta.5

**Comment by moltob** [comment]
Just tested, it looks like its's working now. Thanks a lot for your immediate response and fix!

I'll monitor this obviously, as before it used to be slightly sporadic and also now I'm not using a VPN, in case that mattered. Although it probably doesn't. If it pops up again, I'll keep you posted.

Thanks again!

**Comment by gschier** [comment]
Thanks! Due to the way variable resolution now works, I don't think it's possible for this to happen again, but to re-post if it does!
