### ISSUE TITLE
Unable to edit baseURL

### ISSUE THREAD

**Issue by matdexir** [yaakapp/app#73]
Here is a video describing my experience. 
I'm on Linux using the AppImage. Let me know how I can help with the debugging.

https://github.com/user-attachments/assets/a4901607-c38c-4147-987e-9d009880a369

**Comment by matdexir** [comment]
Agreed! I'm not sure how it renders on other systems but at first glance the current behavior can be quite misleading :).

**Comment by gschier** [comment]
![CleanShot 2024-09-12 at 07 18 39@2x](https://github.com/user-attachments/assets/c153685f-8da4-49b9-8260-dca2f1c01ecb)
