### ISSUE TITLE
Publish to Flatpak

### ISSUE THREAD

**Issue by azzamsa** [yaakapp/app#81]
Hi, 👋🏽 

It would be nice if we could install the app via Flatpak.

Thanks for making Yak open-source! 🥞

**Comment by gschier** [comment]
You're welcome!

Since this isn't a bug report, it should be suggested on https://feedback.yaak.app

It looks like someone already submitted it so give it a vote if you want to be notified of its progress: https://feedback.yaak.app/p/flatpak-and-flathub

**Comment by azzamsa** [comment]
@gschier I think we should make GitHub issue template then.

it consists of a check list containing `[] this is not a feature request` to avoid user confusion.

**Comment by gschier** [comment]
It's on my to-do list for tomorrow :)

**Comment by gschier** [comment]
Issue template added!

![CleanShot 2024-09-12 at 07 08 37@2x](https://github.com/user-attachments/assets/c6952b5c-959f-4c6b-b296-64b2f4f2cb16)
