### ISSUE TITLE
Settings window disappear when moved to another monitor

### ISSUE THREAD

**Issue by leognutzmann** [yaakapp/app#87]
### What happened?

Settings window disappear when moved to another monitor. I minimized every app and it wasn't there.

Steps to reproduce:
1 - Gear in top right -> settings
2 - Move settings window to another monitor
3 - It will desappear
4 - Close Yaak (right button on yaak app icon -> Quit)
5 - Open Yaak again
6 - Gear in top right -> Settings
7 - Minimize Yaak app (macos yellow button)
8 - Unminimize
It will show up again in the starting position

Mac OS version: 14.0 (23A344)
Apple M1 Pro
16 GB
Yaak version: Version 2024.8.2 (20240828.162440)

### Version

2024.8.2

### What operating system are you on?

macOS

**Comment by gschier** [comment]
This is now live in https://yaak.app/blog/2024.10.0-beta.6
