### ISSUE TITLE
Wrong windows start icon path after install

### ISSUE THREAD

**Issue by bumpyy** [yaakapp/app#92]
### What happened?

The shortcut path has an extra ".exe" after install.

![image](https://github.com/user-attachments/assets/4d1b181e-c337-4620-9311-3376f1273a36)

I'm using windows 10.

### Version

2024.9.0

### What operating system are you on?

Windows

**Comment by gschier** [comment]
Looks like Tauri patched this recently so going to try upgrading the deps and re-releasing

**Comment by gschier** [comment]
Fixed in 2024.9.1
